#!/usr/bin/env python
# -*- coding: utf-8 -*-


#    IFRY - isfreyareleased.com is a static website generator based on
#    stats gathered from launchpad.
#
#    Copyright (C) 2014  Gabriel Perren, Jochen Breuer
#
#    This program is free software: you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation, either version 3 of the License, or
#    (at your option) any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with this program.  If not, see <http://www.gnu.org/licenses/>.


import os
import urllib
import time
import datetime
from jinja2 import Template, Environment, FileSystemLoader

"""
Retrieves the number of bugs left until the arrival of the next elementary OS release.

Run it via console with: ./hlti
"""

milestone = "freya-rc1"
codename = "Freya RC1"
PRODUCTION = True

if PRODUCTION:
    env = Environment(loader=FileSystemLoader('/srv/http/isisisreleasedyet.com/lib/jinja_templates'))
else:
    env = Environment(loader=FileSystemLoader('jinja_templates'))

time_stamp = datetime.datetime.fromtimestamp(time.time()).strftime('%Y-%m-%d@%H:%M:%S UTC+1')

# Get Launchpad data.
f = urllib.urlopen("https://launchpad.net/elementary/+milestone/" + milestone)
s = f.read()
f.close()

# Write data to temp file.
ff = open("temp.del", "w")
ff.write(s)
ff.close()


# Find number of bugs left.
bugs_line = 500

b_new = 0
b_incomp = 0
b_conf = 0
b_triaged = 0
b_inprog = 0
b_fix_committed = 0

temp = open("temp.del", "r")
for i, line in enumerate(temp):

        # New bugs.
        if 'span class="statusNEW">' in line and i < bugs_line:
                a = temp.next()
                b = a.split('<strong>')
                c = b[1].split('</strong>')
                b_new = int(c[0])

        # Incomplete bugs.
        if 'span class="statusINCOMPLETE">' in line and i < bugs_line:
                a = temp.next()
                b = a.split('<strong>')
                c = b[1].split('</strong>')
                b_incomp = int(c[0])

        # Confirmed bugs.
        if 'span class="statusCONFIRMED">' in line and i < bugs_line:
                a = temp.next()
                b = a.split('<strong>')
                c = b[1].split('</strong>')
                b_conf = int(c[0])

        # Triaged bugs.
        if 'span class="statusTRIAGED">' in line and i < bugs_line:
                a = temp.next()
                b = a.split('<strong>')
                c = b[1].split('</strong>')
                b_triaged = int(c[0])

        # In progress bugs.
        if 'span class="statusINPROGRESS">' in line and i < bugs_line:
                a = temp.next()
                b = a.split('<strong>')
                c = b[1].split('</strong>')
                b_inprog = int(c[0])

        # In progress bugs.
        if 'span class="statusFIXCOMMITTED">' in line and i < bugs_line:
                a = temp.next()
                b = a.split('<strong>')
                c = b[1].split('</strong>')
                b_fix_committed = int(c[0])

# Delete temp file.
os.remove('temp.del')

bugs = b_new + b_incomp + b_conf + b_triaged + b_inprog + b_fix_committed

message = "issues left until {}. ".format(codename)
if bugs >= 15:
    message += 'Quit moaning.'
elif bugs >= 10:
    message += 'Getting there.'
elif bugs >= 5:
    message += 'Countdown begins!'
elif bugs >= 2:
    message += 'Soooo close!'
elif bugs == 1:
    message += 'JUST ONE MORE TO GO!'

# get jinja template and print to stdout
script_template = env.get_template("index.html")
print(script_template.render({ "milestone": milestone, "codename": codename, "bugs": bugs, "time_stamp": time_stamp, "message": message }))
