#!/usr/bin/env python
# -*- coding: utf-8 -*-

import os
import urllib
import time
import datetime
from jinja2 import Template, Environment, FileSystemLoader

"""
Retrieves the number of bugs left until the arrival of elementary OS Isis beta1.
"""

PRODUCTION = True

if PRODUCTION:
    env = Environment(loader=FileSystemLoader('/srv/http/isisisreleasedyet.com/lib/jinja_templates'))
else:
    env = Environment(loader=FileSystemLoader('jinja_templates'))

time_stamp = datetime.datetime.fromtimestamp(time.time()).strftime('%Y-%m-%d@%H:%M:%S UTC+1')

# Get Launchpad data.
f = urllib.urlopen("https://launchpad.net/elementary/+milestone/isis-beta1")
s = f.read()
f.close()

# Write data to temp file.
ff = open("temp.del", "w")
ff.write(s)
ff.close()


# Find number of bugs left.
temp = open("temp.del", "r")
for i, line in enumerate(temp):

        # New bugs.
        if 'span class="statusNEW">' in line and i < 450:
                a = temp.next()
                b = a.split('<strong>')
                c = b[1].split('</strong>')
                b_new = int(c[0])

        # Incomplete bugs.
        if 'span class="statusINCOMPLETE">' in line and i < 450:
                a = temp.next()
                b = a.split('<strong>')
                c = b[1].split('</strong>')
                b_incomp = int(c[0])

        # Confirmed bugs.
        if 'span class="statusCONFIRMED">' in line and i < 450:
                a = temp.next()
                b = a.split('<strong>')
                c = b[1].split('</strong>')
                b_conf = int(c[0])

        # In progress bugs.
        if 'span class="statusINPROGRESS">' in line and i < 450:
                a = temp.next()
                b = a.split('<strong>')
                c = b[1].split('</strong>')
                b_inprog = int(c[0])

# Delete temp file.
os.remove('temp.del')


bugs = b_new + b_incomp + b_conf + b_inprog

message = ""
if bugs >= 15:
        message = 'issues left until Isis beta1. Quit moaning.'
elif bugs >= 10:
        message = 'issues left until Isis beta1. Getting there.'
elif bugs >= 5:
        message = 'issues left until Isis beta1. Countdown begins!'
elif bugs >= 1:
        message = 'issues left until Isis beta1. Soooo close!'
elif bugs == 1:
        message = 'bug left until Isis beta1. JUST ONE MORE TO GO!'

# get jinja template and print to stdout
script_template = env.get_template("index.html")
print(script_template.render({ "bugs": bugs , "time_stamp": time_stamp, "message": message }))
